/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'crsf' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-Compiler:STDIN:UART&CMSIS@1.0.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_UART_CMSIS      /* CMSIS-Compiler STDIN: UART: CMSIS */
/* ARM::CMSIS-Compiler:STDOUT:UART&CMSIS@1.0.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_UART_CMSIS     /* CMSIS-Compiler STDOUT: UART: CMSIS */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.1 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS Driver:USART@3.0.0 */
#define RTE_CMSIS_Driver_USART1         /* Driver USART1  */
#define RTE_CMSIS_Driver_USART2         /* Driver USART2  */
#define RTE_CMSIS_Driver_USART3         /* Driver USART3  */
#define RTE_CMSIS_Driver_USART4         /* Driver USART4  */
#define RTE_CMSIS_Driver_USART5         /* Driver USART5  */
#define RTE_CMSIS_Driver_USART6         /* Driver USART6  */
#define RTE_CMSIS_Driver_USART7         /* Driver USART7  */
#define RTE_CMSIS_Driver_USART8         /* Driver USART8  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART10        /* Driver USART10 */
#define RTE_CMSIS_Driver_USART11        /* Driver USART11 */
#define RTE_CMSIS_Driver_USART12        /* Driver USART12 */
#define RTE_CMSIS_Driver_USART13        /* Driver USART13 */
#define RTE_CMSIS_Driver_USART14        /* Driver USART14 */
#define RTE_CMSIS_Driver_USART15        /* Driver USART15 */
#define RTE_CMSIS_Driver_USART21        /* Driver USART21 (LPUART1) */
#define RTE_CMSIS_Driver_USART22        /* Driver USART22 (LPUART2) */
#define RTE_CMSIS_Driver_USART23        /* Driver USART23 (LPUART3) */
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32l4xx.h"


#endif /* RTE_COMPONENTS_H */
